### ISSUE TITLE
Download to logs/

### ISSUE THREAD

**Issue by ahmetb** [paulmey/inspect-azure-vhd#2]
Downloading many log files into current working dir is probably not the best idea. It'd be nice to either default to `logs/` or allow user to specify.

**Comment by paulmey** [comment]
I'll probably go further and have some way of supplying some file globs and then point to a dir where it recreates the tree for the download files. Sounds good?

**Comment by ahmetb** [comment]
cool

**Comment by paulmey** [comment]
fixed in master. Defaults to 'out/' in the current directory, but can be overridden using `-outputPath=somepath/`...
